project:
  type: website

website:
  title: "ValidMind"
  sidebar:
    logo: ValidMind-logo-color.svg
    style: "docked"
    background: "light"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



