project:
  type: website
  post-render: make python-docs
website:
  favicon: validmind.png
  title: "ValidMind"
  google-analytics: G-S46CKWPNSS
  search: 
    location: sidebar
    type: textbox
  page-navigation: true
  repo-url: https://github.com/validmind/documentation/
  repo-subdir: site/
  repo-actions: [edit, issue]

  navbar:
    logo: guide/ValidMind-logo-color.svg
    background: white
    title: false
    pinned: true

    left:
      - text: "Get Started"
        file: guide/get-started.qmd
      - text: "Guides"
        file: guide/guides.qmd
      - text: "{{< fa cube >}} Developer Framework"
        menu:
        - text: "{{< fa rocket >}} Get Started"
          file: guide/get-started-developer-framework.qmd
        - text: "{{< fa cubes >}} Supported Models"
          file: guide/supported-models.qmd
        - text: "---"
        - text: "{{< fa code >}} CODE SAMPLES"
        - text: "{{< fa book >}} Quickstart · `Customer Churn` · `Binary Classification`"
          file: notebooks/quickstart_customer_churn_full_suite.ipynb
        - text: "{{< fa book-open-reader >}} More Samples · `LLM` · `NLP` · `Time Series` · `Etc.`"
          file: guide/samples-jupyter-notebooks.qmd
        - text: "{{< fa download >}} Download Samples · `notebooks.zip`"
          file: notebooks.zip
        - text: "{{< fa hand-point-right >}} Try it on Jupyter Hub {{< fa hand-point-left >}}"
          file: https://jupyterhub.validmind.com/
        - text: "---"
        - text:  "{{< fa vial >}} TESTING"
        - text: "{{< fa flask-vial >}} Run Tests & Test Suites"
          file: guide/testing-overview.qmd
        - text: "{{< fa microscope >}} Test Descriptions"
          file: guide/test-descriptions.qmd
        - text: "---"
        - text: "{{< fa book >}} REFERENCE"
        - text: "{{< fa external-link >}} Developer Framework"
          file: validmind/validmind.html
          target: _blank
      - text: "FAQ"
        file: guide/faq.qmd
      - text: "Support"
        file: guide/support.qmd
      - text: "validmind.com {{< fa external-link >}}"
        file: https://validmind.com/
        target: _blank


  sidebar: 
    - title: "Home"
      style: docked
      collapse: true
      collapse-level: 2
      collapse-below: sm

      contents:
        - index.qmd

    - title: "Get Started"
      contents:
        - text: "Get Started"
          file: guide/get-started.qmd
        - text: "---"
        - text: "Quickstart"
          file: guide/quickstart.qmd
        - text: "DEVELOPER FRAMEWORK — 10 Min"
          contents:
          - guide/try-developer-framework-with-jupyterhub.qmd
          - guide/try-developer-framework-with-docker.qmd
          - guide/try-developer-framework-with-colab.qmd
        - text: "PLATFORM UI — 15 min"
          contents:
          - guide/explore-example-documentation-project.qmd
          - guide/create-your-first-documentation-project.qmd
          - guide/upload-to-documentation-project.qmd
#        - text: "Join Our Community" 
#         file: guide/join-community.qmd
        - guide/next-steps.qmd
        - text: "---"
        - text: "OVERVIEW"
          contents:
          - guide/overview.qmd
          - guide/overview-model-documentation.qmd
          - guide/overview-model-risk-management.qmd
#          - guide/overview-product-tour.qmd
#          - guide/editions-and-features.qmd
          - text: "Software license agreement"
            file: guide/license-agreement.qmd
        - text: "Join our closed beta!"
          file: guide/join-closed-beta.qmd
        - text: "Releases"
          contents:
            - text: "January 18, 2024"
              file: releases/2024-jan-18/highlights.qmd
            - text: "December 13, 2023"
              file: releases/2023-dec-13/highlights.qmd
            - text: "November 9, 2023"
              file: releases/2023-nov-09/highlights.qmd
            - text: "October 25, 2023"
              file: releases/2023-oct-25/highlights.qmd
              contents:
                - text: "Enhancements"
                  file: releases/2023-oct-25/enhancement.qmd
                - text: "Bug fixes"
                  file: releases/2023-oct-25/bug.qmd
                - text: "Documentation updates"
                  file: releases/2023-oct-25/documentation.qmd
            - text: "September 27, 2023"
              file: releases/2023-sep-27/highlights.qmd
              contents:
                - text: "Enhancements"
                  file: releases/2023-sep-27/enhancement.qmd
                - text: "Documentation"
                  file: releases/2023-sep-27/documentation.qmd
            - text: "August 15, 2023"
              file: releases/2023-aug-15/highlights.qmd
            - guide/release-notes-2023-jul-24.qmd
            - guide/release-notes-2023-jun-22.qmd
            - guide/release-notes-2023-may-30.qmd
        - text: "---"
        - guide/glossary.qmd
        - text: "---"
        - text: "RELEASES"
        - text: "Join our closed beta!"
          file: guide/join-closed-beta.qmd
        - text: "Release notes"
          contents:
          - text: "November 9, 2023"
            file: releases/2023-nov-09/highlights.qmd
          - text: "October 25, 2023"
            file: releases/2023-oct-25/highlights.qmd
            contents:
              - text: "Enhancements"
                file: releases/2023-oct-25/enhancement.qmd
              - text: "Bug fixes"
                file: releases/2023-oct-25/bug.qmd
              - text: "Documentation updates"
                file: releases/2023-oct-25/documentation.qmd
          - text: "September 27, 2023"
            file: releases/2023-sep-27/highlights.qmd
            contents:
              - text: "Enhancements"
                file: releases/2023-sep-27/enhancement.qmd
              - text: "Documentation"
                file: releases/2023-sep-27/documentation.qmd
          - text: "August 15, 2023"
            file: releases/2023-aug-15/highlights.qmd
          - guide/release-notes-2023-jul-24.qmd
          - guide/release-notes-2023-jun-22.qmd
          - guide/release-notes-2023-may-30.qmd
 
    - title: "Guides"
      contents:
        - guide/guides.qmd
#        - text: "---"
#        - guide/login.qmd
        - text: "---"
        - text: "CONFIGURATION"
        - guide/configure-aws-privatelink.qmd
#        - guide/configure-sso.qmd
#        - guide/configure-workflows.qmd
#        - guide/configure-templates.qmd
#        - guide/configure-test-plans.qmd
#        - guide/manage-users-and-roles.qmd
        - guide/store-credentials-in-env-file.qmd
        - text: "---"
        - text: "MODEL INVENTORY"
        - guide/register-models-in-model-inventory.qmd
        - guide/edit-model-inventory-fields.qmd
        - text: "---"
        - text: "DOCUMENTATION TEMPLATES"
        - guide/configure-documentation-project-templates.qmd
        - guide/swap-documentation-project-templates.qmd
        - text: "---"
        - text: "DOCUMENTATION PROJECTS"
        - guide/create-documentation-project.qmd
        - text: "Document models with the ValidMind UI"
          file: guide/document-models-with-ui.qmd
          contents:
          - guide/view-documentation-guidelines.qmd
          - guide/work-with-content-blocks.qmd
        - text: "Collaborate on documentation projects"
          file: guide/collaborate-on-documentation-projects.qmd
          contents:
          - guide/review-documentation-project.qmd
          - guide/comment-on-documentation-projects.qmd
          - guide/view-documentation-project-activity.qmd
        - guide/submit-for-approval.qmd
        - guide/export-documentation.qmd
        - text: "---"
        - text: "VALIDATION REPORTS"
        - text: "Work with validation reports"
          file: guide/work-with-validation-reports.qmd
          contents:
          - guide/view-validation-guidelines.qmd
          - guide/assign-model-validators.qmd
        - text: "Manage project findings"
          file: guide/manage-project-findings.qmd
          contents:
          - guide/add-project-findings.qmd
          - guide/link-evidence.qmd
        - guide/submit-for-approval.qmd
        - guide/export-documentation.qmd

    - title: "Developer Framework"
      contents:
        - guide/get-started-developer-framework.qmd
        - guide/supported-models.qmd
        - text: "---"
        - guide/install-and-initialize-developer-framework.qmd 
        - text: "---"
        - text: "Run tests & test suites"
          file: guide/testing-overview.qmd
          contents: "notebooks/how_to/*.ipynb"
        - text: "Test descriptions"
          file: guide/test-descriptions.qmd
          contents: tests/**
        - text: "---"
        - text: "Code samples"
          file: guide/samples-jupyter-notebooks.qmd
          contents: "notebooks/code_samples/**"
        - text: "---"
        - text: "Developer Framework Reference {{< fa external-link >}}"
          file: validmind/validmind.html
          target: _blank

    - title: "FAQ"
      contents:
        - guide/faq.qmd
        - text: "---"
        - guide/faq-models.qmd
        - guide/faq-inventory.qmd
        - guide/faq-documentation.qmd
        - guide/faq-testing.qmd
        - guide/faq-integrations.qmd
        - guide/faq-privacy.qmd

    - title: "Support"
      contents:
        - guide/support.qmd
        - text: "---"
        - guide/troubleshooting.qmd

  page-footer:
    background: "#DE257E"
    left: "_© Copyright 2023 ValidMind Inc All Rights Reserved._"
    right:
      - text: "validmind.com {{< fa external-link >}}"
        href: https://validmind.com/
        target: _blank
      - text: "Privacy Policy"
        href: https://validmind.com/privacy-policy/
      - text: "Terms of Use"
        href: https://validmind.com/terms-of-use/
      - icon: github
        href: https://github.com/validmind/documentation
      - icon: linkedin
        href: https://www.linkedin.com/company/validmind/

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: Inter
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: true
    callout-appearance: simple
