project:
  type: website
#  pre-render: make get-source

website:
  title: "ValidMind"
  sidebar:
    logo: guide/ValidMind-logo-color.svg
    style: docked
    background: light
    collapse-level: 2
    search: true
    contents:
    - text: "Welcome"
      file: index.qmd
    - section: "Our platform"
      contents:
      - guide/about.qmd
    - section: "Get started"
      contents:
      - href: guide/getstarteddeveloper.qmd
        text: "As a developer"
      - href: guide/getstartedvalidator.qmd
        text: "As a validator"
      - href: guide/getstartedauditor.qmd
        text: "As an auditor"
    - section: "Reference"
      contents:
      - section: "Jupyter notebooks"
        contents: notebooks/*.ipynb
      - section: "Developer framework"
        file: guide/developerframework.qmd
        contents:
        - validmind/api.md
        - validmind/data_validation_tests.md
        - validmind/model_validation_tests_sklearn.md
        - validmind/test_plans.md
        - validmind/vm_models.md
      - section: "RESTful API"
 
    - section: "Glossary"
    - section: "Support"
    - section: "Release notes"

  page-footer: 
    background: "#C61E6E"
    left: "_© Copyright 2023 ValidMind Inc All Rights Reserved._" 
    right: 
      - icon: github
        href: https://github.com/validmind/documentation
      - icon: linkedin 
        href: https://www.linkedin.com/company/validmind/ 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



