project:
  type: website
#  pre-render: make get-source

website:
  title: "ValidMind"
  sidebar:
    logo: ValidMind-logo-color.svg
    style: "docked"
    background: "light"
    collapse-level: 2
    search: true
    contents:
    - section: "Platform overview"
      contents:
      - href: index.qmd
        text: Home
      - about.qmd
    - section: "Get started"
      contents:
      - getstarteddeveloper.qmd
      - getstartedvalidator.qmd
      - getstartedauditor.qmd
    - section: "Reference"
      contents:
      - section: "Jupyter notebooks"
        contents: "notebooks/*.ipynb"
      - section: "Python library"
        contents: "python-library/*.md"
      - section: "RESTful API"
 
    - section: "Glossary"
    - section: "Support"
    - section: "Release notes"

  page-footer: 
    background: "#C61E6E"
    left: "_© Copyright 2023 ValidMind Inc All Rights Reserved._" 
    right: 
      - icon: github
        href: https://github.com/validmind
#      - icon: twitter 
#        href: https://twitter.com/ 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



